#ifndef SCREEN_CONFIG_H
#define SCREEN_CONFIG_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define SCREEN_TOP_MARGIN 110
#define SCREEN_BOTTOM_MARGIN 10
#define SCREEN_HORIZONTAL_MARGIN 10
#define FPS 1.0f / 60.0f

#endif